services:
  todo_api:
    container_name: todo_api
    build: .
    restart: always
    image: natthaphonarceci/todoapi:lastest
    ports:
      - "8001:8000"
    environment:
      - TZ=Asia/Bangkok
