services:
  todo_api:
    container_name: todo_api
    build: .
    restart: always
    images: natthaphonarceci/todoapi:latest
    # image: natthaphonarceci/todoapi-arm64:latest
    # images: natthaphonarceci/todoapi-amd64:latest
    ports:
      - "8001:8000"
    environment:
      - TZ=Asia/Bangkok
